export default async function handler(req, res) {
  var html = '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
    + '<title>Coffee Personality Quiz | Koffee Review</title>'
    + '<meta name="description" content="5 questions. Find out your coffee personality and which Brisbane cafe matches you. Based on 600+ real reviews.">'
    + '<link rel="canonical" href="https://koffeereview.com.au/quiz"><link rel="icon" href="/logo.webp">'
    + '<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">'
    + '<style>*{margin:0;padding:0;box-sizing:border-box}body{background:#0a0a0c;color:#e2e8f0;font-family:DM Sans,sans-serif;min-height:100vh;-webkit-font-smoothing:antialiased}.c{max-width:520px;margin:0 auto;padding:0 20px 60px}.nav{display:flex;align-items:center;justify-content:space-between;padding:14px 0;border-bottom:1px solid rgba(255,255,255,0.06)}.nav-logo{display:flex;align-items:center;gap:10px;text-decoration:none}.nav-logo img{width:34px;height:34px;border-radius:50%}.nav-logo span{font-family:Bebas Neue,sans-serif;font-size:15px;letter-spacing:3px;color:#E6C073}'
    + '.card{background:rgba(255,255,255,0.04);border:1px solid rgba(255,255,255,0.08);border-radius:20px;padding:28px;margin-top:24px;text-align:center}'
    + '.q-num{display:inline-block;padding:4px 14px;border-radius:20px;font-size:11px;font-weight:700;letter-spacing:2px;background:rgba(230,192,115,0.1);color:#E6C073;border:1px solid rgba(230,192,115,0.2);margin-bottom:16px}'
    + '.q-text{font-size:18px;font-weight:600;color:#fff;line-height:1.5;margin-bottom:20px}'
    + '.opt{display:flex;flex-direction:column;gap:8px}'
    + '.opt-btn{padding:16px;border-radius:14px;background:rgba(255,255,255,0.04);border:2px solid rgba(255,255,255,0.08);color:#fff;font-size:14px;cursor:pointer;font-family:DM Sans,sans-serif;text-align:left;transition:all 0.15s}'
    + '.opt-btn:hover{border-color:rgba(230,192,115,0.4);background:rgba(230,192,115,0.06)}'
    + '.opt-btn:active{transform:scale(0.98)}'
    + '.result{display:none;text-align:center;padding:20px 0}'
    + '.r-emoji{font-size:56px;margin-bottom:12px}'
    + '.r-type{font-family:Bebas Neue,sans-serif;font-size:36px;color:#E6C073;letter-spacing:2px}'
    + '.r-desc{font-size:14px;color:rgba(255,255,255,0.55);line-height:1.7;margin:12px 0 20px}'
    + '.r-cafe{background:rgba(230,192,115,0.04);border:1px solid rgba(230,192,115,0.2);border-radius:14px;padding:16px;margin:12px 0}'
    + '.r-cafe-name{font-family:Bebas Neue,sans-serif;font-size:20px;color:#fff}'
    + '.r-cafe-sub{font-size:12px;color:rgba(255,255,255,0.4)}'
    + '.share-btn{display:inline-block;margin-top:16px;padding:14px 32px;border-radius:14px;background:linear-gradient(135deg,#c8a96e,#E6C073);color:#0a0a0c;font-size:14px;font-weight:700;cursor:pointer;border:none;font-family:DM Sans,sans-serif}'
    + '.again{display:inline-block;margin-top:12px;color:#E6C073;text-decoration:none;font-size:14px}'
    + '.ft{margin-top:32px;padding:20px 0;border-top:1px solid rgba(255,255,255,0.04);text-align:center;font-size:11px;color:rgba(255,255,255,0.3)}.ft a{color:rgba(255,255,255,0.5);text-decoration:none;margin:0 8px}</style>'
    + '</head><body><div class="c">'
    + '<nav class="nav"><a href="/" class="nav-logo"><img src="/logo.webp" alt="KR"><span>KOFFEE REVIEW</span></a></nav>'
    + '<div style="text-align:center;padding:24px 0 0"><div style="font-size:11px;letter-spacing:3px;color:rgba(230,192,115,0.6);margin-bottom:6px">COFFEE QUIZ</div><h1 style="font-family:Bebas Neue,sans-serif;font-size:clamp(28px,7vw,40px);letter-spacing:2px;color:#fff">What Is Your Coffee Personality?</h1><p style="font-size:14px;color:rgba(255,255,255,0.45);margin-top:8px">5 questions. We match you to a real cafe.</p></div>'
    + '<div id="quizArea" class="card"></div>'
    + '<div class="result" id="resultArea"></div>'
    + '<footer class="ft"><a href="/explore">Explore</a><a href="/guess-the-score">Games</a><a href="/blog">Blog</a></footer></div>'
    + '<script>'
    + 'var QS=['
    + '{q:"How do you take your coffee?",opts:[{t:"Flat white or latte — milk is essential",v:"milk"},{t:"Long black or double shot — no milk needed",v:"black"},{t:"Whatever the barista recommends",v:"adventurous"},{t:"I change it up every time",v:"explorer"}]},'
    + '{q:"What flavour profile appeals to you?",opts:[{t:"Chocolate, caramel, nutty — classic and comforting",v:"classic"},{t:"Fruity, bright, acidic — surprise me",v:"fruity"},{t:"Bold, strong, dark — hit me hard",v:"bold"},{t:"Smooth, balanced, clean — nothing extreme",v:"balanced"}]},'
    + '{q:"Pick your ideal cafe vibe:",opts:[{t:"Quiet corner, laptop open, nobody bothers me",v:"quiet"},{t:"Buzzy, busy, people watching",v:"social"},{t:"Hole in the wall, counter service, in and out",v:"quick"},{t:"Beautiful space, I want to photograph it",v:"aesthetic"}]},'
    + '{q:"How far will you travel for good coffee?",opts:[{t:"Walking distance only",v:"local"},{t:"10 min drive, sure",v:"nearby"},{t:"Across the city if it is worth it",v:"dedicated"},{t:"I will plan a weekend around it",v:"obsessed"}]},'
    + '{q:"What matters most in a cafe?",opts:[{t:"The espresso — extraction is everything",v:"purist"},{t:"The latte — milk and coffee in harmony",v:"harmony"},{t:"Consistency — same great cup every visit",v:"reliable"},{t:"Discovery — show me something new",v:"curious"}]}'
    + '];'
    + 'var TYPES={'
    + '"milk-classic-quiet-local-harmony":{type:"The Comfort Drinker",emoji:"\\u2615",desc:"You know what you like and you like it reliable. A well-made latte with chocolate and caramel notes is your happy place. You do not need adventure. You need consistency.",cafe:"Blackout Paddington",score:"7.5",slug:"blackout-paddington-paddington",sub:"Paddington"},'
    + '"milk-classic-social-nearby-reliable":{type:"The Local Regular",emoji:"\\ud83c\\udfe0",desc:"Your cafe knows your order. You sit in the same spot. The barista nods when you walk in. You are the backbone of every good cafe.",cafe:"Brown Dog Cafe",score:"7.3",slug:"brown-dog-cafe-woolloongabba",sub:"Woolloongabba"},'
    + '"black-bold-quick-dedicated-purist":{type:"The Purist",emoji:"\\ud83d\\udd25",desc:"Double shot. No milk. No sugar. No small talk. You taste extraction quality and you know when it is wrong. Cafes fear your palate.",cafe:"Zen Barista",score:"7.8",slug:"zen-barista-manly",sub:"Manly"},'
    + '"black-fruity-quiet-obsessed-curious":{type:"The Specialty Nerd",emoji:"\\ud83e\\uddd0",desc:"You ask about the origin. You know what washed process means. You have opinions about roast profiles. Single origin is not a menu option, it is a lifestyle.",cafe:"Coffee Anthology",score:"7.5",slug:"coffee-anthology-cbd",sub:"CBD"},'
    + '"milk-balanced-aesthetic-nearby-harmony":{type:"The Aesthetic Sipper",emoji:"\\ud83d\\udcf8",desc:"The cafe has to look good and taste good. You photograph the latte art. You notice the fit out. But you also notice when the coffee is average. Both matter.",cafe:"Silipo Coffee",score:"7.8",slug:"silipo-coffee-southport",sub:"Southport"},'
    + '"adventurous-fruity-social-dedicated-curious":{type:"The Explorer",emoji:"\\ud83c\\udf0d",desc:"You have never ordered the same thing twice. New suburbs, new roasters, new origins. Your coffee map has more pins than Google. Every cup is research.",cafe:"Industry Beans",score:"7.5",slug:"industry-beans-newstead-newstead",sub:"Newstead"}'
    + '};'
    + 'var FALLBACKS=['
    + '{type:"The West Ender",emoji:"\\u2728",desc:"Creative, independent, slightly experimental. You gravitate toward owner-operated cafes with personality. West End is your spiritual home.",cafe:"The Twin",score:"7.8",slug:"the-twin-west-end",sub:"West End"},'
    + '{type:"The Early Bird",emoji:"\\ud83c\\udf05",desc:"First in line, pre-7am, double shot to start the day. You believe morning coffee is sacred and the best shots happen before the rush.",cafe:"Coffee Speed Dial",score:"7.5",slug:"coffee-speed-dial-newstead",sub:"Newstead"},'
    + '{type:"The Data Drinker",emoji:"\\ud83d\\udcca",desc:"You check the score before you order. You compare suburbs. You have opinions backed by numbers. You probably built a spreadsheet about your coffee habits.",cafe:"Bellissimo Coffee",score:"7.9",slug:"bellissimo-coffee-bulimba",sub:"Bulimba"},'
    + '{type:"The Hidden Gem Hunter",emoji:"\\ud83d\\udc8e",desc:"You skip the famous names and find the quiet cafes nobody talks about. Your best discoveries are in suburbs your friends have never visited.",cafe:"Clubhouse Nundah",score:"7.5",slug:"clubhouse-nundah",sub:"Nundah"}'
    + '];'
    + 'var round=0;var answers=[];'
    + 'function loadQ(){if(round>=QS.length){showResult();return;}var q=QS[round];var h="<div class=\\"q-num\\">QUESTION "+(round+1)+" OF "+QS.length+"</div><div class=\\"q-text\\">"+q.q+"</div><div class=\\"opt\\">";q.opts.forEach(function(o,i){h+="<button class=\\"opt-btn\\" onclick=\\"pick(\'"+o.v+"\')\\">"+o.t+"</button>";});h+="</div>";document.getElementById("quizArea").innerHTML=h;}'
    + 'function pick(v){answers.push(v);round++;if(navigator.vibrate)navigator.vibrate(20);loadQ();}'
    + 'function showResult(){document.getElementById("quizArea").style.display="none";var key=answers.join("-");var r=TYPES[key];if(!r){r=FALLBACKS[Math.floor(Math.random()*FALLBACKS.length)];}document.getElementById("resultArea").style.display="block";document.getElementById("resultArea").innerHTML="<div class=\\"r-emoji\\">"+r.emoji+"</div><div class=\\"r-type\\">"+r.type+"</div><div class=\\"r-desc\\">"+r.desc+"</div><div class=\\"r-cafe\\"><div style=\\"font-size:10px;letter-spacing:2px;color:rgba(230,192,115,0.5);margin-bottom:6px\\">YOUR CAFE MATCH</div><div class=\\"r-cafe-name\\">"+r.cafe+" ("+r.score+")</div><div class=\\"r-cafe-sub\\">"+r.sub+"</div><a href=\\"/review/"+r.slug+"\\" style=\\"display:inline-block;margin-top:8px;color:#E6C073;font-size:12px;text-decoration:none\\">See full review &rarr;</a></div><button class=\\"share-btn\\" onclick=\\"shareQuiz(\'"+r.type+"\',"+"\'"+r.cafe+"\'"+")\\">Share My Result</button><br><a href=\\"/quiz\\" class=\\"again\\">Take Again</a><br><a href=\\"/explore\\" class=\\"again\\" style=\\"margin-top:6px\\">Explore &rarr;</a>";}'
    + 'function shareQuiz(type,cafe){var txt="My coffee personality: "+type+"\\nMy cafe match: "+cafe+"\\n\\nWhat\'s yours? koffeereview.com.au/quiz";if(navigator.share){navigator.share({text:txt}).catch(function(){});}else if(navigator.clipboard){navigator.clipboard.writeText(txt);alert("Copied!");}}'
    + 'loadQ();'
    + '<\/script></body></html>';
  res.setHeader("Content-Type", "text/html; charset=utf-8");
  res.setHeader("Cache-Control", "public, s-maxage=3600, stale-while-revalidate=86400");
  res.status(200).send(html);
}
