export default async function handler(req, res) {
  var year = new Date().getFullYear();
  var html = '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
    + '<title>My Coffee List | Koffee Review</title><meta name="robots" content="noindex">'
    + '<link rel="icon" href="/logo.webp"><link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">'
    + '<style>*{margin:0;padding:0;box-sizing:border-box}body{background:#0a0a0c;color:#e2e8f0;font-family:DM Sans,sans-serif;-webkit-font-smoothing:antialiased}.c{max-width:620px;margin:0 auto;padding:0 20px 60px}.nav{display:flex;align-items:center;justify-content:space-between;padding:14px 0;border-bottom:1px solid rgba(255,255,255,0.06)}.nav-logo{display:flex;align-items:center;gap:10px;text-decoration:none}.nav-logo img{width:34px;height:34px;border-radius:50%}.nav-logo span{font-family:Bebas Neue,sans-serif;font-size:15px;letter-spacing:3px;color:#E6C073}.tab{display:flex;gap:0;margin:20px 0;background:rgba(255,255,255,0.02);border:1px solid rgba(255,255,255,0.06);border-radius:14px;overflow:hidden}.tab-btn{flex:1;padding:12px;text-align:center;font-size:13px;font-weight:600;cursor:pointer;border:none;background:transparent;color:rgba(255,255,255,0.4);font-family:DM Sans,sans-serif;transition:all 0.2s}.tab-btn.active{background:rgba(230,192,115,0.1);color:#E6C073}.empty{text-align:center;padding:40px 0;color:rgba(255,255,255,0.3);font-size:14px;line-height:1.6}.card{display:flex;align-items:center;gap:12px;background:rgba(255,255,255,0.03);border:1px solid rgba(255,255,255,0.06);border-radius:14px;padding:14px 16px;margin-bottom:8px;text-decoration:none;color:inherit}.card:hover{border-color:rgba(230,192,115,0.25)}.ft{margin-top:32px;padding:20px 0;border-top:1px solid rgba(255,255,255,0.04);text-align:center;font-size:11px;color:rgba(255,255,255,0.3)}.ft a{color:rgba(255,255,255,0.5);text-decoration:none;margin:0 8px}</style>'
    + '</head><body><div class="c">'
    + '<nav class="nav"><a href="/" class="nav-logo"><img src="/logo.webp" alt="KR"><span>KOFFEE REVIEW</span></a></nav>'
    + '<div style="padding:24px 0 0"><div style="font-size:10px;letter-spacing:3px;color:rgba(230,192,115,0.5);margin-bottom:8px">YOUR LIST</div><h1 style="font-family:Bebas Neue,sans-serif;font-size:clamp(28px,7vw,40px);letter-spacing:2px;color:#fff">My Coffee List</h1></div>'
    + '<div class="tab"><button class="tab-btn active" onclick="showTab(\'saved\')">Saved ♥</button><button class="tab-btn" onclick="showTab(\'visited\')">Visited ✓</button></div>'
    + '<div style="display:flex;gap:0;margin-bottom:16px;background:rgba(255,255,255,0.02);border:1px solid rgba(255,255,255,0.06);border-radius:14px;overflow:hidden"><div style="flex:1;text-align:center;padding:12px 8px"><div style="font-family:Bebas Neue,sans-serif;font-size:24px;color:#E6C073" id="savedCount">0</div><div style="font-size:9px;letter-spacing:2px;color:rgba(255,255,255,0.3)">SAVED</div></div><div style="flex:1;text-align:center;padding:12px 8px"><div style="font-family:Bebas Neue,sans-serif;font-size:24px;color:#4ade80" id="visitedCount">0</div><div style="font-size:9px;letter-spacing:2px;color:rgba(255,255,255,0.3)">VISITED</div></div><div style="flex:1;text-align:center;padding:12px 8px"><div style="font-family:Bebas Neue,sans-serif;font-size:24px;color:#fff" id="totalCount">600+</div><div style="font-size:9px;letter-spacing:2px;color:rgba(255,255,255,0.3)">TOTAL</div></div></div>'
    + '<div id="savedList"></div><div id="visitedList" style="display:none"></div>'
    + '<div class="empty" id="emptyMsg" style="display:none">No cafes saved yet.<br>Tap ♥ Save on any review page to build your list.</div>'
    + '<div style="margin-top:24px"><a href="/explore" style="display:flex;align-items:center;justify-content:space-between;padding:13px 16px;background:rgba(230,192,115,0.03);border:1px solid rgba(230,192,115,0.12);border-radius:14px;text-decoration:none;color:#E6C073;font-size:13px">Explore &rarr;</a></div>'
    + '<footer class="ft"><a href="/explore">Explore</a><a href="/leaderboard">Leaderboard</a><a href="/blog">Blog</a></footer></div>'
    + '<script>'
    + 'var saved=JSON.parse(localStorage.getItem("kr_saved")||"[]");'
    + 'var visited=JSON.parse(localStorage.getItem("kr_visited")||"[]");'
    + 'document.getElementById("savedCount").textContent=saved.length;'
    + 'document.getElementById("visitedCount").textContent=visited.length;'
    + 'function makeCard(slug,type){var name=slug.replace(/-/g," ").replace(/\\b\\w/g,function(l){return l.toUpperCase();});return\'<a href="/review/\'+slug+\'" class="card"><div style="flex:1;min-width:0"><div style="font-size:14px;font-weight:600;color:#fff">\'+name+\'</div><div style="font-size:11px;color:rgba(255,255,255,0.35);margin-top:2px">Tap to view review</div></div><div style="font-size:12px;color:rgba(255,255,255,0.2)">&rarr;</div></a>\';}'
    + 'function renderList(arr,elId){var el=document.getElementById(elId);if(!arr.length){el.innerHTML="";return;}el.innerHTML=arr.map(function(s){return makeCard(s);}).join("");}'
    + 'renderList(saved,"savedList");renderList(visited,"visitedList");'
    + 'if(!saved.length)document.getElementById("emptyMsg").style.display="block";'
    + 'function showTab(tab){document.getElementById("savedList").style.display=tab==="saved"?"block":"none";document.getElementById("visitedList").style.display=tab==="visited"?"block":"none";document.querySelectorAll(".tab-btn").forEach(function(b,i){b.className="tab-btn"+(i===(tab==="saved"?0:1)?" active":"");});document.getElementById("emptyMsg").style.display=(tab==="saved"&&!saved.length)||(tab==="visited"&&!visited.length)?"block":"none";document.getElementById("emptyMsg").innerHTML=tab==="saved"?"No cafes saved yet.<br>Tap \\u2665 Save on any review page.":"No cafes visited yet.<br>Tap \\u2713 Been here on any review page.";}'
    + '<\/script></body></html>';
  res.setHeader("Content-Type", "text/html; charset=utf-8");
  res.setHeader("Cache-Control", "no-cache");
  res.status(200).send(html);
}
